# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17WzeSEJpYKAGwaHWFiIVt5n3VCU2us9o
"""

classificacao = ('Vasco', 'Flamengo', 'Fluminense', 'Botafogo', 'Chapecoense', 
                 'Santos', 'Coritiba', 'Palmeiras', 'Cruzeiro', 'Madureira',
                 'São Caetano', 'América', 'Paraná')
ordemAlfa = sorted(classificacao)

print(f'\nOs cinco primeiros são: {classificacao[:4]}')
print(f'\nOs cinco últimos são: {classificacao[-4:]}')

for posicao, time in enumerate(classificacao):
  if time == 'Chapecoense':
    print(f'\nA {time} está na {posicao + 1}ª posição na classificação!')

print(f'\nOs times em ordem alfabética:')
for c in ordemAlfa:
  print(c)